### GET healthz
GET http://localhost:20120/healthz

### GET readyz
GET http://localhost:20120/readyz

### GET startz
GET http://localhost:20120/startz


### POST ingest
POST http://localhost:20120/ingest
Authorization: SignalStash sk-sigstash-Opq9PmfC64D54WRvbLQvmDZnICNaYlEM0FKYJoCf3sRXvavfFijq6uPf-g4fS9RR
Content-Type: `application/x-protobuf`
Content-Length: 0



### POST ingest (protobuf example)
POST http://localhost:20120/ingest
Content-Type: application/x-protobuf
Authorization: SignalStash sk-sigstash-Opq9PmfC64D54WRvbLQvmDZnICNaYlEM0FKYJoCf3sRXvavfFijq6uPf-g4fS9RR

< ./sample_sensor_data.bin


### List Keys
GET http://localhost:20120/api/keys
Authorization: SignalStash sk-sigstash-Opq9PmfC64D54WRvbLQvmDZnICNaYlEM0FKYJoCf3sRXvavfFijq6uPf-g4fS9RR

### Create Key
POST http://localhost:20120/api/keys
Content-Type: application/json
Authorization: SignalStash sk-sigstash-Opq9PmfC64D54WRvbLQvmDZnICNaYlEM0FKYJoCf3sRXvavfFijq6uPf-g4fS9RR

{
    "user_id": "ciroque-admin"
}

### Revoke Key
DELETE http://localhost:20120/api/keys/sk-sigstash-4F6zIat-Hz60E_KYmTjZyS1imJ8DYmCDZBaSGWeXoYDsEU7Xgd7Owgvgjtgr5e0q
Authorization: SignalStash sk-sigstash-Opq9PmfC64D54WRvbLQvmDZnICNaYlEM0FKYJoCf3sRXvavfFijq6uPf-g4fS9RR
#DELETE http://localhost:20120/api/keys/{{api-key-uuid}}
# Replace {{api-key-uuid}} with the actual UUID returned from the Create Key endpoint