### GET healthz
GET http://localhost:20120/healthz

### GET readyz
GET http://localhost:20120/readyz

### GET startz
GET http://localhost:20120/startz


### POST ingest
POST http://localhost:20120/ingest
Authorization: SignalStash sk-sigstash-Opq9PmfC64D54WRvbLQvmDZnICNaYlEM0FKYJoCf3sRXvavfFijq6uPf-g4fS9RR
Content-Type: `application/x-protobuf`
Content-Length: 0



### POST ingest (protobuf example)
POST http://localhost:20120/ingest
Content-Type: application/x-protobuf
Authorization: {{standard_api_key}}

< ./sample_sensor_data.bin


### List Keys
GET http://localhost:20120/api/keys
Authorization: {{ admin_api_key }}

### Create Key
POST http://localhost:20120/api/keys
Content-Type: application/json
Authorization: {{ admin_api_key }}

{
    "user_id": "ciroque-spl-iot"
}

### Revoke Key
DELETE http://localhost:20120/api/keys/sk-sigstash-cS4KeAOVIXJHeaaOmZnwGZy-y_4LxVntM9B2YedJhso8p8naoFhVjQ0JksDYp2Bd
Authorization: {{ admin_api_key }}
#DELETE http://localhost:20120/api/keys/{{api-key-uuid}}
# Replace {{api-key-uuid}} with the actual UUID returned from the Create Key endpoint