### GET healthz
GET http://localhost:20120/healthz

### GET readyz
GET http://localhost:20120/readyz

### GET startz
GET http://localhost:20120/startz


### POST ingest
POST http://localhost:20120/ingest

Content-Type: `application/x-protobuf`
Content-Length: 0



### POST ingest (protobuf example)
POST http://localhost:20120/ingest
Content-Type: application/x-protobuf

< ./sample_sensor_data.bin
