name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Rust
        uses: actions/setup-rust@v1
        with:
          rust-version: 1.88
      - name: Install protoc
        run: sudo apt-get update && sudo apt-get install -y protobuf-compiler
      - name: Build
        run: cargo build --release --all-targets
      - name: Run tests
        run: cargo test --all-targets --all-features
      - name: Check formatting
        run: cargo fmt -- --check
      - name: Clippy lint
        run: cargo clippy --all-targets --all-features -- -D warnings
