name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: rust:1.88
    steps:
      - name: Checkout repository code:
        uses: actions/checkout@v4

      - name: Install protoc
        run: sudo apt-get update && sudo apt-get install -y protobuf-compiler

      - name: Build
        run: cargo build --release --all-targets

      - name: Run tests
        run: cargo test --all-targets --all-features

      - name: Check formatting
        run: cargo fmt -- --check

      - name: Clippy lint
        run: cargo clippy --all-targets --all-features -- -D warnings
