name: Build and Sign Docker Image

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-sign-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
      security-events: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Install Cosign
        uses: sigstore/cosign-installer@e1523de7571e31dbe865fd2e80c5c7c23ae71eb4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

#      - name: Build Docker image
#        id: docker_build
#        run: |
#          docker build -t ghcr.io/${{ github.actor }}/signalstashrs:${{ github.sha }} .


      - name: Build Docker Image
        id: docker-build-and-push
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ghcr.io/signalstashrs:latest,ghcr.io/signalstashrs:${{github.sha}}
      - name: Sign Docker image with Cosign (keyless)
        run: |
          cosign sign --yes ghcr.io/${{ github.actor }}/signalstashrs:${{ steps.docker-build-and-push.outputs.digest }}
#          cosign sign --yes ghcr.io/${{ github.actor }}/signalstashrs:${{ github.sha }}
