name: Build and Sign Docker Image

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-sign-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write # Needed for keyless signing with cosign
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build Docker image
        run: |
          docker build -t ghcr.io/${{ github.actor }}/signalstashrs:${{ github.sha }} .
      - name: Push Docker image
        run: |
          docker push ghcr.io/${{ github.actor }}/signalstashrs:${{ github.sha }}
      - name: Install Cosign
        uses: sigstore/cosign-installer@v3.4.0
      - name: Sign Docker image with Cosign (keyless)
        env:
          COSIGN_EXPERIMENTAL: 1
        run: |
          cosign sign --yes ghcr.io/${{ github.repository }}/signalstashrs:${{ github.sha }}
